# .github/workflows/check-filename.yml (Фінальна версія для devops-app-repo)

name: Filename Check Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/LAB-5_*
  pull_request:
    branches:
      - main
      - develop
      - feature/LAB-5_*

jobs:
  check-filename:
    runs-on: ubuntu-latest
    
    env:
      REGISTRY_SERVER: ${{ secrets.GCR_LOGIN_SERVER }} # europe-west3-docker.pkg.dev
      
    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    # 1. Автентифікація з GCP та отримання токену
    # Ця дія встановлює credentials для gcloud
    - name: Google Cloud Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 2. Налаштування Docker для використання gcloud (GCP Helper)
    # Це є КРИТИЧНО важливим для коректного pull з AR
    - name: Configure Docker to use Artifact Registry
      run: |
        # Встановлюємо gcloud як credential helper для Docker
        gcloud auth configure-docker $REGISTRY_SERVER --quiet
      
    # 3. Виконання CI-задачі, використовуючи ВАШ власний Docker-образ
    # uses: docker://... виконує pull на основі попередньо встановленої конфігурації Docker
    - name: Run Filename Check using Custom Docker Image
      uses: docker://europe-west3-docker.pkg.dev/directed-cove-452818-r6/myroslavababiichuk09/ci-checker-image-myroslavababiichuk:0.1.0
      with:
        entrypoint: /bin/bash 
        args: checker-scripts/check-filename.sh
